name: Main workflow
on:
  issues:
    types: [opened,edited]

permissions:
  contents: write

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
    
      - env:
          issue_data: ${{ toJson(github.event.issue.body) }}
        run: | 
          python --version
          echo "Deploy main from commit | ${{ github.event.head_commit.message }} |"
          python src/create_json.py
      - run: |
          git config --global user.name 'Platform Automation Bot'
          git config --global user.email 'platform.bot@kopoutech.com'
          git checkout -B "ID-${{ (github.event.issue.id) }}-automated-branch"
          git add *.json
          git commit -m "[SKIP CI] Automated PR"
          git push --set-upstream origin "ID-${{ (github.event.issue.id) }}-automated-branch"
          gh pr create --title "Automated Deployment PR" --body "PR raised from Issue - ${{ (github.event.issue.id) }} - ${{ (github.event.issue.url) }}" 
   