name: Main workflow
on:
  issues:
    types: [opened,edited]

permissions:
  contents: write
  pull-requests: write
  issues: write 

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    if: ${{ startswith(github.event.issue.title, '[SERVICE REQUEST]' ) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
    
      - env:
          issue_data: ${{ toJson(github.event.issue.body) }}
        run: | 
          python --version
          echo "Deploy main from commit | ${{ github.event.head_commit.message }} |"
          python src/create_json.py
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ACTION_URL='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          gh issue comment ${{ (github.event.issue.number) }} \
              --body "Your issue is being processed using GitHub actions $ACTION_URL. Branch - $BRANCH_NAME . PR Link: $PR_URL"
          if [ -f created.nokeep ]; then
            git config --global user.name 'Platform Automation Bot'
            git config --global user.email 'platform.bot@kopoutech.com'
            BRANCH_NAME='${{ (github.event.issue.number) }}-ID-automated-branch'
            git checkout -B "$BRANCH_NAME"
            git add *.json
            git commit -m "[SKIP CI] Automated PR"
            git push --set-upstream origin "$BRANCH_NAME"
            gh pr create --title "Automated Deployment PR | Closes #${{ (github.event.issue.number) }}" --body "Closes #${{ (github.event.issue.number) }} PR raised from Issue - ${{ (github.event.issue.number) }} - ${{ (github.event.issue.url) }}" > pr-url.nokeep
            PR_URL=$(cat pr-url.nokeep)
            gh issue comment ${{ (github.event.issue.number) }} \
              --body "A successful PR has been raised against your request. Action Url : $ACTION_URL | Branch - $BRANCH_NAME | PR Link: $PR_URL .\n Your request will be provisioned once PR is merged"
          fi
           
          if [ -f failed_error.nokeep ]; then
            ERROR_DATA=$(cat failed_error.nokeep)
            gh issue comment ${{ (github.event.issue.number) }} \
              --body "We are sorry to inform you that your request has failed. Error message received - [$ERROR_DATA] - See $ACTION_URL "
          fi
   