name: Main workflow

on:
  pull_request:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: | 
          python --version
          echo "Deploy main from commit ${{ github.event.head_commit.message }}"
   