name: Main workflow

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: | 
          python --version
          echo "Deploy main from commit ${{ github.event.head_commit.message }}"
          python src/invoke.py
      - run: |
          git config --global user.name 'Platform Automation Bot'
          git config --global user.email 'platform.bot@kopoutech.com'
          git add *.keep
          git commit -m "[SKIP CI] Automated deployment check"
          git push
   